#设置项目启动端口
server:
  port: 9010
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  #设置数据库数据源
  datasource:
    url: jdbc:mysql://120.77.169.200:3306/hartend_crm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: hartend@123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 120.77.169.200
    # 数据库索引 默认0
    database: 0
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
    password: hartend@123
